package com.sea.model;

public class CountTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_count_time.cpType
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer cptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_count_time.grouptype
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer grouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_count_time.times
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_count_time.cpType
     *
     * @return the value of t_count_time.cpType
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getCptype() {
        return cptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_count_time.cpType
     *
     * @param cptype the value for t_count_time.cpType
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setCptype(Integer cptype) {
        this.cptype = cptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_count_time.grouptype
     *
     * @return the value of t_count_time.grouptype
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getGrouptype() {
        return grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_count_time.grouptype
     *
     * @param grouptype the value for t_count_time.grouptype
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setGrouptype(Integer grouptype) {
        this.grouptype = grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_count_time.times
     *
     * @return the value of t_count_time.times
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_count_time.times
     *
     * @param times the value for t_count_time.times
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setTimes(Integer times) {
        this.times = times;
    }
}