package com.sea.model;

public class CpCourrent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.id
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.userid
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.money
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.buyTime
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private Long buytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.stageNum
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private String stagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.cpType
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private Integer cptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.groupType
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private Integer grouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cp_courrent.content
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.id
     *
     * @return the value of t_cp_courrent.id
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.id
     *
     * @param id the value for t_cp_courrent.id
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.userid
     *
     * @return the value of t_cp_courrent.userid
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.userid
     *
     * @param userid the value for t_cp_courrent.userid
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.money
     *
     * @return the value of t_cp_courrent.money
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.money
     *
     * @param money the value for t_cp_courrent.money
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.buyTime
     *
     * @return the value of t_cp_courrent.buyTime
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public Long getBuytime() {
        return buytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.buyTime
     *
     * @param buytime the value for t_cp_courrent.buyTime
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setBuytime(Long buytime) {
        this.buytime = buytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.stageNum
     *
     * @return the value of t_cp_courrent.stageNum
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public String getStagenum() {
        return stagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.stageNum
     *
     * @param stagenum the value for t_cp_courrent.stageNum
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setStagenum(String stagenum) {
        this.stagenum = stagenum == null ? null : stagenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.cpType
     *
     * @return the value of t_cp_courrent.cpType
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public Integer getCptype() {
        return cptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.cpType
     *
     * @param cptype the value for t_cp_courrent.cpType
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setCptype(Integer cptype) {
        this.cptype = cptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.groupType
     *
     * @return the value of t_cp_courrent.groupType
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public Integer getGrouptype() {
        return grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.groupType
     *
     * @param grouptype the value for t_cp_courrent.groupType
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setGrouptype(Integer grouptype) {
        this.grouptype = grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cp_courrent.content
     *
     * @return the value of t_cp_courrent.content
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cp_courrent.content
     *
     * @param content the value for t_cp_courrent.content
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}