package com.sea.model;

public class CqStage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cq_stage.id
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cq_stage.stagetime
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Long stagetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cq_stage.stagenumber
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private String stagenumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cq_stage.id
     *
     * @return the value of t_cq_stage.id
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cq_stage.id
     *
     * @param id the value for t_cq_stage.id
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cq_stage.stagetime
     *
     * @return the value of t_cq_stage.stagetime
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Long getStagetime() {
        return stagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cq_stage.stagetime
     *
     * @param stagetime the value for t_cq_stage.stagetime
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setStagetime(Long stagetime) {
        this.stagetime = stagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cq_stage.stagenumber
     *
     * @return the value of t_cq_stage.stagenumber
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public String getStagenumber() {
        return stagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cq_stage.stagenumber
     *
     * @param stagenumber the value for t_cq_stage.stagenumber
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setStagenumber(String stagenumber) {
        this.stagenumber = stagenumber == null ? null : stagenumber.trim();
    }
}