package com.sea.model;

public class Current {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.id
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.stageId
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private String stageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.stageTime
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private Long stagetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.bb
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private Integer bb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.bs
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private Integer bs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.sb
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private Integer sb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_current.ss
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    private Integer ss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.id
     *
     * @return the value of t_current.id
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.id
     *
     * @param id the value for t_current.id
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.stageId
     *
     * @return the value of t_current.stageId
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public String getStageid() {
        return stageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.stageId
     *
     * @param stageid the value for t_current.stageId
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setStageid(String stageid) {
        this.stageid = stageid == null ? null : stageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.stageTime
     *
     * @return the value of t_current.stageTime
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public Long getStagetime() {
        return stagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.stageTime
     *
     * @param stagetime the value for t_current.stageTime
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setStagetime(Long stagetime) {
        this.stagetime = stagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.bb
     *
     * @return the value of t_current.bb
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public Integer getBb() {
        return bb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.bb
     *
     * @param bb the value for t_current.bb
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setBb(Integer bb) {
        this.bb = bb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.bs
     *
     * @return the value of t_current.bs
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public Integer getBs() {
        return bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.bs
     *
     * @param bs the value for t_current.bs
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setBs(Integer bs) {
        this.bs = bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.sb
     *
     * @return the value of t_current.sb
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public Integer getSb() {
        return sb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.sb
     *
     * @param sb the value for t_current.sb
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setSb(Integer sb) {
        this.sb = sb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_current.ss
     *
     * @return the value of t_current.ss
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public Integer getSs() {
        return ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_current.ss
     *
     * @param ss the value for t_current.ss
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    public void setSs(Integer ss) {
        this.ss = ss;
    }
}