package com.sea.model;

public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.id
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.bb
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer bb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.bs
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer bs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.sb
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer sb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.ss
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    private Integer ss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.id
     *
     * @return the value of t_history.id
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.id
     *
     * @param id the value for t_history.id
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.bb
     *
     * @return the value of t_history.bb
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getBb() {
        return bb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.bb
     *
     * @param bb the value for t_history.bb
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setBb(Integer bb) {
        this.bb = bb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.bs
     *
     * @return the value of t_history.bs
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getBs() {
        return bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.bs
     *
     * @param bs the value for t_history.bs
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setBs(Integer bs) {
        this.bs = bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.sb
     *
     * @return the value of t_history.sb
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getSb() {
        return sb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.sb
     *
     * @param sb the value for t_history.sb
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setSb(Integer sb) {
        this.sb = sb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.ss
     *
     * @return the value of t_history.ss
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public Integer getSs() {
        return ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.ss
     *
     * @param ss the value for t_history.ss
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    public void setSs(Integer ss) {
        this.ss = ss;
    }
}