package com.sea.dao;

import com.sea.model.CountTime;

public interface CountTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int insert(CountTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int insertSelective(CountTime record);
}