package com.sea.dao;

import com.sea.model.CountTime;

public interface CountTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 12:48:28 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 12:48:28 CST 2014
     */
    int insert(CountTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 12:48:28 CST 2014
     */
    int insertSelective(CountTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 12:48:28 CST 2014
     */
    CountTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 12:48:28 CST 2014
     */
    int updateByPrimaryKeySelective(CountTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_count_time
     *
     * @mbggenerated Fri Oct 10 12:48:28 CST 2014
     */
    int updateByPrimaryKey(CountTime record);
    
    
}