package com.sea.dao;

import com.sea.model.CpHistory;

public interface CpHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cp_history
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cp_history
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    int insert(CpHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cp_history
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    int insertSelective(CpHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cp_history
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    CpHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cp_history
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    int updateByPrimaryKeySelective(CpHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cp_history
     *
     * @mbggenerated Sat Oct 11 16:04:36 CST 2014
     */
    int updateByPrimaryKey(CpHistory record);
}