package com.sea.dao;

import java.util.List;
import java.util.Map;

import com.sea.model.CqStage;

public interface CqStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cq_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cq_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int insert(CqStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cq_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int insertSelective(CqStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cq_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    CqStage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cq_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int updateByPrimaryKeySelective(CqStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cq_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int updateByPrimaryKey(CqStage record);
    
    List<CqStage> getListByPage(Map<?,?> map);
}