package com.sea.dao;

import com.sea.model.Current;

public interface CurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_current
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_current
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int insert(Current record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_current
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int insertSelective(Current record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_current
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    Current selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_current
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int updateByPrimaryKeySelective(Current record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_current
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int updateByPrimaryKey(Current record);
}