package com.sea.dao;

import com.sea.model.History;

public interface HistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int insert(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int insertSelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    History selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int updateByPrimaryKeySelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbggenerated Fri Oct 10 13:00:18 CST 2014
     */
    int updateByPrimaryKey(History record);
}