package com.sea.dao;

import java.util.List;
import java.util.Map;

import com.sea.model.JxStage;

public interface JxStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int insert(JxStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int insertSelective(JxStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    JxStage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int updateByPrimaryKeySelective(JxStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jx_stage
     *
     * @mbggenerated Fri Oct 10 16:32:03 CST 2014
     */
    int updateByPrimaryKey(JxStage record);
    
    
    List<JxStage> getListByPage(Map<?,?> map);
}